# Generated by Django 3.2.9 on 2021-11-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20211114_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
