# Generated by Django 3.2.9 on 2021-11-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_actor_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
