# Generated by Django 3.2.9 on 2021-11-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_cinema_cinemamoviescreening'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemamoviescreening',
            old_name='end_date',
            new_name='screening_start_at',
        ),
        migrations.RemoveField(
            model_name='cinemamoviescreening',
            name='start_date',
        ),
        migrations.AddField(
            model_name='cinemamoviescreening',
            name='minutes_duration',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
