# Generated by Django 3.2.9 on 2021-11-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20211121_1213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cinema',
            unique_together={('name', 'location')},
        ),
    ]
