# Generated by Django 3.2.9 on 2021-11-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_cinema_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemamoviescreening',
            name='sold_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
