# Generated by Django 3.2.9 on 2021-12-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20211204_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='finances',
            field=models.FloatField(default=0),
        ),
    ]
