# Generated by Django 3.2.9 on 2021-12-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
