# Generated by Django 3.2.9 on 2021-12-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': (('can_dislike', 'Can dislike movie'),)},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
