
DIFFICULTY_CHOICE_EASY = 1
DIFFICULTY_CHOICE_MEDIUM = 2
DIFFICULTY_CHOICE_HARD = 3
DIFFICULTY_CHOICE_INSANE = 4


DIFFICULTY_CHOICES = (
    (DIFFICULTY_CHOICE_EASY, 'Easy'),
    (DIFFICULTY_CHOICE_MEDIUM, 'medium'),
    (DIFFICULTY_CHOICE_HARD, 'hard'),
    (DIFFICULTY_CHOICE_INSANE, 'insane'),
)
